version: 2
jobs:
  build:
    docker:
      - image: pragya1996/complete-docker-new
    steps:
      - checkout
      - run:
          name: Running unit tests
          command: python -m unittest discover -v
